spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://152.42.163.114:5434/alumni_db
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mail:
    host: smtp.gmail.com
    port: 587
    username: "vannraruos@gmail.com"
    password: "klmcbchpzqszhlhz"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  swagger-ui:
    path: /api

server:
  port: 8181  # Add your desired port number here

ACCESS_TOKEN_PRIVATE_KEY_PATH: keys/access-token-private.key
ACCESS_TOKEN_PUBLIC_KEY_PATH: keys/access-token-public.key
# This is for the refresh token
REFRESH_TOKEN_PRIVATE_KEY_PATH: keys/refresh-token-private.key
REFRESH_TOKEN_PUBLIC_KEY_PATH: keys/refresh-token-public.key