spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: postgres
    password: lyhou123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update


  mail:
    host: smtp.gmail.com
    port: 587
    username: "vannraruos@gmail.com"
    password: "klmcbchpzqszhlhz"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  swagger-ui:
    path: /api
file_storage:
  image_location: "/filestorage/images/"
  client_path: "/images/**"
server:
  port: 8181

file:
  storage-dir: "filestorage/images/"
  client-dir: "/images/**"
  storage-dir1: "cvStorage/cv/"
  client-dir1: "/cv/**"  # Add your desired port number here

ACCESS_TOKEN_PRIVATE_KEY_PATH: keys/access-token-private.key
ACCESS_TOKEN_PUBLIC_KEY_PATH: keys/access-token-public.key
# This is for the refresh token
REFRESH_TOKEN_PRIVATE_KEY_PATH: keys/refresh-token-private.key
REFRESH_TOKEN_PUBLIC_KEY_PATH: keys/refresh-token-public.key